### ISSUE TITLE
"Attempt to free invalid pointer" error

### ISSUE THREAD

**Issue by arighnac** [chronolaw/ngx_google_perftools_profiler_module#1]
Getting this error, while trying to run any nginx related command (nginx -V etc.)
```
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x55ef8c535fb0 
```
Configuration, build and installation process were done successfully.
I suspect dynamically loading tcmalloc leads to this crash (see [this](https://github.com/gperftools/gperftools/issues/1066)). But I have also tried adding `-ltcmalloc` to the compilation and linking parameters (`--with-cc-opt` and `--with-ld-opt`), but I still get the same error.

@chronolaw Could you please help here? Kind of urgent.

**Comment by chronolaw** [comment]
Sorry, perhaps I can not help you at this point，you may try official Nginx gperf module.

**Comment by arighnac** [comment]
official Nginx gperf module only has the CPU profiler, I do need the heap profiler as well. That's where `-ltcmalloc` comes into play.
